// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1dHkatvl2m_yhH_vJC07xkmPYj6YR-zw',
    appId: '1:526967959777:web:254df31a326d36d60f87a0',
    messagingSenderId: '526967959777',
    projectId: 'financial-goal-77955',
    authDomain: 'financial-goal-77955.firebaseapp.com',
    storageBucket: 'financial-goal-77955.appspot.com',
    measurementId: 'G-0EY8JWJQY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAepQw3BgiixUhqeA2JiXnaeCr5bQkaPW0',
    appId: '1:526967959777:android:b4b2f0682c9897210f87a0',
    messagingSenderId: '526967959777',
    projectId: 'financial-goal-77955',
    storageBucket: 'financial-goal-77955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQq5BCuuv3Hpn8X9iGzqUCKedlihKNF1A',
    appId: '1:526967959777:ios:dc84e38d14699fe40f87a0',
    messagingSenderId: '526967959777',
    projectId: 'financial-goal-77955',
    storageBucket: 'financial-goal-77955.appspot.com',
    iosBundleId: 'com.example.financialGoal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQq5BCuuv3Hpn8X9iGzqUCKedlihKNF1A',
    appId: '1:526967959777:ios:400abbb05ffa74c50f87a0',
    messagingSenderId: '526967959777',
    projectId: 'financial-goal-77955',
    storageBucket: 'financial-goal-77955.appspot.com',
    iosBundleId: 'com.example.financialGoal.RunnerTests',
  );
}
